export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const LOGOUT = "LOGOUT";
export const GET_TICKETS = "GET_TICKETS";
export const DELETE_TICKET = "DELETE_TICKET";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const GET_COMPLAINTS = "GET_COMPLAINTS";
export const DELETE_COMPLAINT = "DELETE_COMPLAINT";
